Repository CaseLabJava/CaseLabJavaCRM, pull requests merged in 2023-11, with the labels that each got.

#27 #27 - Add DTOs for Responses and Requests
  src/main/java/com/greenatom/controller/AuthController.java
  src/main/java/com/greenatom/controller/ClientController.java
  src/main/java/com/greenatom/controller/EmployeeController.java
  src/main/java/com/greenatom/controller/OrderController.java
  src/main/java/com/greenatom/controller/OrderItemController.java
  src/main/java/com/greenatom/controller/ProductController.java
  src/main/java/com/greenatom/controller/UploadDocController.java
  src/main/java/com/greenatom/controller/api/AuthApi.java
  src/main/java/com/greenatom/controller/api/ClientApi.java
  src/main/java/com/greenatom/controller/api/EmployeeApi.java
  src/main/java/com/greenatom/controller/api/OrderApi.java
  src/main/java/com/greenatom/controller/api/OrderItemApi.java
  src/main/java/com/greenatom/controller/api/ProductApi.java
  src/main/java/com/greenatom/controller/api/UploadDocApi.java
  src/main/java/com/greenatom/domain/dto/ClientDTO.java
  src/main/java/com/greenatom/domain/dto/ProductDTO.java
  src/main/java/com/greenatom/domain/dto/ResponseDTO.java
  src/main/java/com/greenatom/domain/dto/client/ClientRequestDTO.java
  src/main/java/com/greenatom/domain/dto/client/ClientResponseDTO.java
  src/main/java/com/greenatom/domain/dto/employee/CreateEmployeeRequestDTO.java
  src/main/java/com/greenatom/domain/dto/employee/EmployeeRequestDTO.java
  src/main/java/com/greenatom/domain/dto/employee/EmployeeResponseDTO.java
  src/main/java/com/greenatom/domain/dto/item/OrderItemRequestDTO.java
  src/main/java/com/greenatom/domain/dto/item/OrderItemResponseDTO.java
  src/main/java/com/greenatom/domain/dto/order/GenerateOrderRequestDTO.java
  src/main/java/com/greenatom/domain/dto/order/OrderRequestDTO.java
  src/main/java/com/greenatom/domain/dto/order/OrderResponseDTO.java
  src/main/java/com/greenatom/domain/dto/order/UploadDocumentRequestDTO.java
  src/main/java/com/greenatom/domain/dto/product/ProductRequestDTO.java
  src/main/java/com/greenatom/domain/dto/product/ProductResponseDTO.java
  src/main/java/com/greenatom/domain/dto/security/AuthDTO.java
  src/main/java/com/greenatom/domain/dto/security/JwtResponse.java
  src/main/java/com/greenatom/domain/dto/security/RefreshJwtRequest.java
  src/main/java/com/greenatom/domain/dto/security/RoleDTO.java
  src/main/java/com/greenatom/domain/mapper/ClientMapper.java
  src/main/java/com/greenatom/domain/mapper/EmployeeCleanMapper.java
  src/main/java/com/greenatom/domain/mapper/EmployeeMapper.java
  src/main/java/com/greenatom/domain/mapper/OrderItemMapper.java
  src/main/java/com/greenatom/domain/mapper/OrderMapper.java
  src/main/java/com/greenatom/domain/mapper/ProductMapper.java
  src/main/java/com/greenatom/security/service/AuthService.java
  src/main/java/com/greenatom/service/ClientService.java
  src/main/java/com/greenatom/service/EmployeeService.java
  src/main/java/com/greenatom/service/OrderItemService.java
  src/main/java/com/greenatom/service/OrderService.java
  src/main/java/com/greenatom/service/ProductService.java
  src/main/java/com/greenatom/service/UploadDocService.java
  src/main/java/com/greenatom/service/impl/ClientServiceImpl.java
  src/main/java/com/greenatom/service/impl/EmployeeServiceImpl.java
  src/main/java/com/greenatom/service/impl/OrderItemServiceImpl.java
  src/main/java/com/greenatom/service/impl/OrderServiceImpl.java
  src/main/java/com/greenatom/service/impl/ProductServiceImpl.java
  src/main/java/com/greenatom/service/impl/UploadDocImpl.java
  src/main/java/com/greenatom/utils/exception/handler/ProductExceptionHandler.java
  src/main/java/com/greenatom/utils/mapper/TranslateRusToEng.java
Labels: enhancement, refactoring

#30 #30 - Update entity model
  src/main/java/com/greenatom/domain/dto/claim/ClaimRequestDTO.java
  src/main/java/com/greenatom/domain/dto/claim/ClaimResponseDTO.java
  src/main/java/com/greenatom/domain/dto/client/ClientRequestDTO.java
  src/main/java/com/greenatom/domain/dto/client/ClientResponseDTO.java
  src/main/java/com/greenatom/domain/dto/courier/CourierRequestDTO.java
  src/main/java/com/greenatom/domain/dto/courier/CourierResponseDTO.java
  src/main/java/com/greenatom/domain/dto/delivery/DeliveryRequestDTO.java
  src/main/java/com/greenatom/domain/dto/delivery/DeliveryResponseDTO.java
  src/main/java/com/greenatom/domain/dto/order/OrderResponseDTO.java
  src/main/java/com/greenatom/domain/dto/preparing_order/PreparingOrderRequestDTO.java
  src/main/java/com/greenatom/domain/dto/preparing_order/PreparingOrderResponseDTO.java
  src/main/java/com/greenatom/domain/entity/Claim.java
  src/main/java/com/greenatom/domain/entity/Client.java
  src/main/java/com/greenatom/domain/entity/Courier.java
  src/main/java/com/greenatom/domain/entity/Delivery.java
  src/main/java/com/greenatom/domain/entity/Employee.java
  src/main/java/com/greenatom/domain/entity/Order.java
  src/main/java/com/greenatom/domain/entity/PreparingOrder.java
  src/main/java/com/greenatom/domain/enums/ClaimStatus.java
  src/main/java/com/greenatom/domain/enums/DeliveryStatus.java
  src/main/java/com/greenatom/domain/enums/DeliveryType.java
  src/main/java/com/greenatom/domain/enums/PreparingOrderStatus.java
  src/main/java/com/greenatom/domain/mapper/ClaimMapper.java
  src/main/java/com/greenatom/domain/mapper/CourierMapper.java
  src/main/java/com/greenatom/domain/mapper/DeliveryMapper.java
  src/main/java/com/greenatom/domain/mapper/PreparingOrderMapper.java
  src/main/java/com/greenatom/repository/ClaimRepository.java
  src/main/java/com/greenatom/repository/CourierRepository.java
  src/main/java/com/greenatom/repository/DeliveryRepository.java
  src/main/java/com/greenatom/repository/PreparingOrderRepository.java
  src/main/java/com/greenatom/service/impl/OrderServiceImpl.java
  src/main/resources/db/changelog/db.changelog-master.xml
  src/main/resources/db/changelog/v.0.0.1/order-lifecycle-update-0.0.4.xml
Labels: refactoring

#31 fix: change database field from employee_id to courier id
  src/main/resources/db/changelog/v.0.0.1/order-lifecycle-update-0.0.4.xml
Labels: fix

#34 #34 - Add claim lifecycle and email support
  pom.xml
  src/main/java/com/greenatom/controller/ClaimController.java
  src/main/java/com/greenatom/controller/api/ClaimApi.java
  src/main/java/com/greenatom/domain/enums/ClaimStatus.java
  src/main/java/com/greenatom/repository/ClaimRepository.java
  src/main/java/com/greenatom/service/ClaimService.java
  src/main/java/com/greenatom/service/OrderService.java
  src/main/java/com/greenatom/service/impl/ClaimServiceImpl.java
  src/main/java/com/greenatom/service/impl/OrderServiceImpl.java
  src/main/java/com/greenatom/utils/exception/ClaimException.java
  src/main/java/com/greenatom/utils/exception/message/ClaimErrorMessage.java
  src/main/resources/application.yml
Labels: enhancement
