Repository CaseLabJava/CaseLabJavaCRM, pull requests merged in 2023-10, with the labels that each got.

#1 #1 - Initialize Spring Boot layers
  pom.xml
  src/main/java/com/greenatom/controller/ClientController.java
  src/main/java/com/greenatom/controller/EmployeeController.java
  src/main/java/com/greenatom/controller/EstimateController.java
  src/main/java/com/greenatom/controller/RequestController.java
  src/main/java/com/greenatom/controller/SuccessfulWorkController.java
  src/main/java/com/greenatom/controller/SupplyController.java
  src/main/java/com/greenatom/domain/dto/ClientDTO.java
  src/main/java/com/greenatom/domain/dto/EmployeeDTO.java
  src/main/java/com/greenatom/domain/dto/EstimateDTO.java
  src/main/java/com/greenatom/domain/dto/RequestDTO.java
  src/main/java/com/greenatom/domain/dto/SuccessfulWorkDTO.java
  src/main/java/com/greenatom/domain/dto/SupplyDTO.java
  src/main/java/com/greenatom/domain/entity/Client.java
  src/main/java/com/greenatom/domain/entity/Employee.java
  src/main/java/com/greenatom/domain/entity/Estimate.java
  src/main/java/com/greenatom/domain/entity/Request.java
  src/main/java/com/greenatom/domain/entity/SuccessfulWork.java
  src/main/java/com/greenatom/domain/entity/Supply.java
  src/main/java/com/greenatom/domain/enums/JobPosition.java
  src/main/java/com/greenatom/domain/mapper/ClientMapper.java
  src/main/java/com/greenatom/domain/mapper/EmployeeMapper.java
  src/main/java/com/greenatom/domain/mapper/EntityMapper.java
  src/main/java/com/greenatom/domain/mapper/EstimateMapper.java
  src/main/java/com/greenatom/domain/mapper/RequestMapper.java
  src/main/java/com/greenatom/domain/mapper/SuccessfulWorkMapper.java
  src/main/java/com/greenatom/domain/mapper/SupplyMapper.java
  src/main/java/com/greenatom/repository/ClientRepository.java
  src/main/java/com/greenatom/repository/EmployeeRepository.java
  src/main/java/com/greenatom/repository/EstimateRepository.java
  src/main/java/com/greenatom/repository/RequestRepository.java
  src/main/java/com/greenatom/repository/SuccessfulWorkRepository.java
  src/main/java/com/greenatom/repository/SupplyRepository.java
  src/main/java/com/greenatom/service/ClientService.java
  src/main/java/com/greenatom/service/EmployeeService.java
  src/main/java/com/greenatom/service/EstimateService.java
  src/main/java/com/greenatom/service/RequestService.java
  src/main/java/com/greenatom/service/SuccessfulWorkService.java
  src/main/java/com/greenatom/service/SupplyService.java
  src/main/java/com/greenatom/service/impl/ClientServiceImpl.java
  src/main/java/com/greenatom/service/impl/EmployeeServiceImpl.java
  src/main/java/com/greenatom/service/impl/EstimateServiceImpl.java
  src/main/java/com/greenatom/service/impl/RequestServiceImpl.java
  src/main/java/com/greenatom/service/impl/SuccessfulWorkServiceImpl.java
  src/main/java/com/greenatom/service/impl/SupplyServiceImpl.java
Labels: good first issue

#3 Feat/swagger
  .gitignore
  pom.xml
  src/main/java/com/greenatom/config/swagger/SwaggerConfig.java
  src/main/java/com/greenatom/controller/AuthController.java
  src/main/java/com/greenatom/controller/api/AuthApi.java
  src/main/java/com/greenatom/domain/dto/AuthDto.java
  src/main/java/com/greenatom/domain/dto/EmployeeDTO.java
  src/main/java/com/greenatom/domain/dto/JwtResponse.java
  src/main/java/com/greenatom/domain/dto/RefreshJwtRequest.java
  src/main/java/com/greenatom/domain/dto/RoleDto.java
  src/main/java/com/greenatom/security/config/Config.java
  src/main/resources/application.yml
Labels: enhancement

#4 #4 Rework entities & add exceptions
  pom.xml
  src/main/java/com/greenatom/config/aop/LoggingAspect.java
  src/main/java/com/greenatom/config/security/SecurityConfig.java
  src/main/java/com/greenatom/controller/CartProductController.java
  src/main/java/com/greenatom/controller/EstimateController.java
  src/main/java/com/greenatom/controller/ProductController.java
  src/main/java/com/greenatom/controller/SuccessfulWorkController.java
  src/main/java/com/greenatom/controller/SupplyController.java
  src/main/java/com/greenatom/domain/dto/CartProductDTO.java
  src/main/java/com/greenatom/domain/dto/ClientDTO.java
  src/main/java/com/greenatom/domain/dto/EmployeeDTO.java
  src/main/java/com/greenatom/domain/dto/ProductDTO.java
  src/main/java/com/greenatom/domain/dto/RequestDTO.java
  src/main/java/com/greenatom/domain/dto/ResponseDTO.java
  src/main/java/com/greenatom/domain/dto/RoleDto.java
  src/main/java/com/greenatom/domain/entity/CartProduct.java
  src/main/java/com/greenatom/domain/entity/Client.java
  src/main/java/com/greenatom/domain/entity/Employee.java
  src/main/java/com/greenatom/domain/entity/Product.java
  src/main/java/com/greenatom/domain/entity/Request.java
  src/main/java/com/greenatom/domain/entity/SuccessfulWork.java
  src/main/java/com/greenatom/domain/entity/Supply.java
  src/main/java/com/greenatom/domain/mapper/CartProductMapper.java
  src/main/java/com/greenatom/domain/mapper/EstimateMapper.java
  src/main/java/com/greenatom/domain/mapper/ProductMapper.java
  src/main/java/com/greenatom/domain/mapper/SuccessfulWorkMapper.java
  src/main/java/com/greenatom/domain/mapper/SupplyMapper.java
  src/main/java/com/greenatom/repository/CartProductRepository.java
  src/main/java/com/greenatom/repository/ProductRepository.java
  src/main/java/com/greenatom/repository/SupplyRepository.java
  src/main/java/com/greenatom/service/CartProductService.java
  src/main/java/com/greenatom/service/EstimateService.java
  src/main/java/com/greenatom/service/ProductService.java
  src/main/java/com/greenatom/service/SuccessfulWorkService.java
  src/main/java/com/greenatom/service/impl/CartProductServiceImpl.java
  src/main/java/com/greenatom/service/impl/EmployeeServiceImpl.java
  src/main/java/com/greenatom/service/impl/EstimateServiceImpl.java
  src/main/java/com/greenatom/service/impl/ProductServiceImpl.java
  src/main/java/com/greenatom/service/impl/RequestServiceImpl.java
  src/main/java/com/greenatom/service/impl/SuccessfulWorkServiceImpl.java
  src/main/java/com/greenatom/service/impl/SupplyServiceImpl.java
  src/main/java/com/greenatom/utils/data/SetupDataLoader.java
  src/main/java/com/greenatom/utils/exception/EmailAlreadyUsedException.java
  src/main/java/com/greenatom/utils/exception/UsernameAlreadyUsedException.java
  src/main/java/com/greenatom/utils/exception/handler/CustomExceptionHandler.java
Labels: enhancement

#6 Feat/generation
  .gitignore
  pom.xml
  src/main/java/com/greenatom/controller/RequestController.java
  src/main/java/com/greenatom/controller/api/RequestApi.java
  src/main/java/com/greenatom/domain/dto/ClientDTO.java
  src/main/java/com/greenatom/domain/dto/EmployeeDTO.java
  src/main/java/com/greenatom/domain/entity/CartProduct.java
  src/main/java/com/greenatom/domain/entity/Client.java
  src/main/java/com/greenatom/domain/entity/Employee.java
  src/main/java/com/greenatom/service/impl/RequestServiceImpl.java
  src/main/java/com/greenatom/utils/data/SetupDataLoader.java
  src/main/java/com/greenatom/utils/generator/request/Constants.java
  src/main/java/com/greenatom/utils/generator/request/OrderGenerator.java
  src/main/java/com/greenatom/utils/generator/request/TextUtils.java
  src/main/resources/application.yml
Labels: enhancement

#10 Add cicd pipelines. Add Dockerfile and docker-compose.yaml.
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/sonar.yml
  .github/workflows/test coverage.yml
  Dockerfile
  codecov.yml
  docker-compose.yaml
  pom.xml
  src/main/resources/application-build.yaml
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yml
Labels: enhancement

#9 Feat/doc assign
  src/main/java/com/greenatom/config/aop/LoggingAspect.java
  src/main/java/com/greenatom/config/swagger/annotation/AccessDeniedResponse.java
  src/main/java/com/greenatom/controller/EmployeeController.java
  src/main/java/com/greenatom/controller/OrderController.java
  src/main/java/com/greenatom/controller/OrderItemController.java
  src/main/java/com/greenatom/controller/api/OrderApi.java
  src/main/java/com/greenatom/controller/api/OrderItemApi.java
  src/main/java/com/greenatom/domain/dto/EmployeeCleanDTO.java
  src/main/java/com/greenatom/domain/dto/OrderDTO.java
  src/main/java/com/greenatom/domain/dto/OrderItemDTO.java
  src/main/java/com/greenatom/domain/dto/item/OrderItemDTO.java
  src/main/java/com/greenatom/domain/dto/item/OrderItemRequest.java
  src/main/java/com/greenatom/domain/dto/order/GenerateOrderRequest.java
  src/main/java/com/greenatom/domain/dto/order/OrderDTO.java
  src/main/java/com/greenatom/domain/dto/order/OrderRequest.java
  src/main/java/com/greenatom/domain/entity/OrderItem.java
  src/main/java/com/greenatom/domain/enums/OrderStatus.java
  src/main/java/com/greenatom/domain/mapper/EmployeeCleanMapper.java
  src/main/java/com/greenatom/domain/mapper/OrderItemMapper.java
  src/main/java/com/greenatom/domain/mapper/OrderMapper.java
  src/main/java/com/greenatom/repository/OrderItemRepository.java
  src/main/java/com/greenatom/repository/ProductRepository.java
  src/main/java/com/greenatom/service/EmployeeService.java
  src/main/java/com/greenatom/service/OrderItemService.java
  src/main/java/com/greenatom/service/OrderService.java
  src/main/java/com/greenatom/service/impl/EmployeeServiceImpl.java
  src/main/java/com/greenatom/service/impl/OrderItemServiceImpl.java
  src/main/java/com/greenatom/service/impl/OrderServiceImpl.java
  src/main/java/com/greenatom/utils/date/DateTimeUtils.java
  src/main/java/com/greenatom/utils/exception/OrderException.java
  src/main/java/com/greenatom/utils/exception/OrderItemException.java
  src/main/java/com/greenatom/utils/exception/handler/OrderExceptionHandler.java
  src/main/java/com/greenatom/utils/exception/handler/OrderItemExceptionHandler.java
  src/main/java/com/greenatom/utils/exception/message/ErrorMessage.java
Labels: enhancement

#12 #12 - Employee API, Paging, minor fixes
  pom.xml
  src/main/java/com/greenatom/config/swagger/annotation/AccessDeniedResponse.java
  src/main/java/com/greenatom/controller/EmployeeController.java
  src/main/java/com/greenatom/controller/OrderController.java
  src/main/java/com/greenatom/controller/api/AuthApi.java
  src/main/java/com/greenatom/controller/api/EmployeeApi.java
  src/main/java/com/greenatom/controller/api/OrderApi.java
  src/main/java/com/greenatom/controller/api/OrderItemApi.java
  src/main/java/com/greenatom/domain/enums/OrderStatus.java
  src/main/java/com/greenatom/domain/mapper/EmployeeCleanMapper.java
  src/main/java/com/greenatom/repository/OrderRepository.java
  src/main/java/com/greenatom/service/EmployeeService.java
  src/main/java/com/greenatom/service/OrderService.java
  src/main/java/com/greenatom/service/exceptions/PasswordsNotMatchingException.java
  src/main/java/com/greenatom/service/impl/EmployeeServiceImpl.java
  src/main/java/com/greenatom/service/impl/OrderServiceImpl.java
  src/main/java/com/greenatom/utils/exception/OrderException.java
  src/main/java/com/greenatom/utils/exception/handler/OrderExceptionHandler.java
  src/main/java/com/greenatom/utils/exception/handler/OrderItemExceptionHandler.java
  src/main/java/com/greenatom/utils/exception/message/ClientErrorMessage.java
  src/main/java/com/greenatom/utils/exception/message/EmployeeErrorMessage.java
  src/main/java/com/greenatom/utils/exception/message/OrderErrorMessage.java
  src/main/java/com/greenatom/utils/exception/message/OrderItemErrorMessage.java
Labels: enhancement

#14 Fix/jwt generation admin
  src/main/java/com/greenatom/security/jwt/JwtCore.java
  src/main/java/com/greenatom/security/service/AuthService.java
  src/main/java/com/greenatom/service/impl/EmployeeServiceImpl.java
  src/main/java/com/greenatom/utils/data/SetupDataLoader.java
  src/main/java/com/greenatom/utils/exception/handler/CustomExceptionHandler.java
Labels: enhancement

#19 feat: added swagger documentation for ProductController
  src/main/java/com/greenatom/controller/ProductController.java
  src/main/java/com/greenatom/controller/api/ProductApi.java
  src/main/java/com/greenatom/utils/exception/message/ProductErrorMessage.java
Labels: documentation

#20 #20 - Add ResponseEntity to ClientController's methods, add Api for ClientController
  src/main/java/com/greenatom/controller/ClientController.java
  src/main/java/com/greenatom/controller/api/ClientAPI.java
  src/main/java/com/greenatom/service/ClientService.java
Labels: documentation

#24 #24 - Add order finish & minor fixes
  src/main/java/com/greenatom/controller/AuthController.java
  src/main/java/com/greenatom/controller/ClientController.java
  src/main/java/com/greenatom/controller/EmployeeController.java
  src/main/java/com/greenatom/controller/OrderController.java
  src/main/java/com/greenatom/controller/OrderItemController.java
  src/main/java/com/greenatom/controller/ProductController.java
  src/main/java/com/greenatom/controller/api/AuthApi.java
  src/main/java/com/greenatom/controller/api/ClientApi.java
  src/main/java/com/greenatom/controller/api/EmployeeApi.java
  src/main/java/com/greenatom/controller/api/OrderApi.java
  src/main/java/com/greenatom/controller/api/OrderItemApi.java
  src/main/java/com/greenatom/domain/dto/AuthDTO.java
  src/main/java/com/greenatom/domain/dto/EmployeeCleanDTO.java
  src/main/java/com/greenatom/domain/dto/EmployeeDTO.java
  src/main/java/com/greenatom/domain/dto/RoleDTO.java
  src/main/java/com/greenatom/domain/dto/order/OrderDTO.java
  src/main/java/com/greenatom/domain/entity/Order.java
  src/main/java/com/greenatom/domain/enums/OrderStatus.java
  src/main/java/com/greenatom/security/service/AuthService.java
  src/main/java/com/greenatom/service/ClientService.java
  src/main/java/com/greenatom/service/EmployeeService.java
  src/main/java/com/greenatom/service/OrderService.java
  src/main/java/com/greenatom/service/ProductService.java
  src/main/java/com/greenatom/service/exceptions/PasswordsNotMatchingException.java
  src/main/java/com/greenatom/service/impl/ClientServiceImpl.java
  src/main/java/com/greenatom/service/impl/EmployeeServiceImpl.java
  src/main/java/com/greenatom/service/impl/OrderItemServiceImpl.java
  src/main/java/com/greenatom/service/impl/OrderServiceImpl.java
  src/main/java/com/greenatom/service/impl/ProductServiceImpl.java
  src/main/java/com/greenatom/service/impl/UploadDocImpl.java
  src/main/java/com/greenatom/utils/exception/OrderException.java
  src/main/java/com/greenatom/utils/exception/handler/OrderExceptionHandler.java
Labels: enhancement

#25 #25 - Add handlers & code fixes
  src/main/java/com/greenatom/controller/EmployeeController.java
  src/main/java/com/greenatom/controller/OrderController.java
  src/main/java/com/greenatom/controller/ProductController.java
  src/main/java/com/greenatom/controller/api/AuthApi.java
  src/main/java/com/greenatom/domain/entity/Client.java
  src/main/java/com/greenatom/domain/entity/Employee.java
  src/main/java/com/greenatom/domain/entity/Order.java
  src/main/java/com/greenatom/domain/entity/OrderItem.java
  src/main/java/com/greenatom/domain/entity/Product.java
  src/main/java/com/greenatom/security/jwt/JwtCore.java
  src/main/java/com/greenatom/security/service/AuthService.java
  src/main/java/com/greenatom/service/ProductService.java
  src/main/java/com/greenatom/service/impl/ClientServiceImpl.java
  src/main/java/com/greenatom/service/impl/EmployeeServiceImpl.java
  src/main/java/com/greenatom/service/impl/OrderItemServiceImpl.java
  src/main/java/com/greenatom/service/impl/OrderServiceImpl.java
  src/main/java/com/greenatom/service/impl/ProductServiceImpl.java
  src/main/java/com/greenatom/service/impl/UserDetailsServiceImpl.java
  src/main/java/com/greenatom/utils/exception/AuthException.java
  src/main/java/com/greenatom/utils/exception/ClientException.java
  src/main/java/com/greenatom/utils/exception/EmailAlreadyUsedException.java
  src/main/java/com/greenatom/utils/exception/EmployeeException.java
  src/main/java/com/greenatom/utils/exception/OrderException.java
  src/main/java/com/greenatom/utils/exception/OrderItemException.java
  src/main/java/com/greenatom/utils/exception/ProductException.java
  src/main/java/com/greenatom/utils/exception/UsernameAlreadyUsedException.java
  src/main/java/com/greenatom/utils/exception/handler/AccessDeniedExceptionHandler.java
  src/main/java/com/greenatom/utils/exception/handler/AuthExceptionHandler.java
  src/main/java/com/greenatom/utils/exception/handler/ClientExceptionHandler.java
  src/main/java/com/greenatom/utils/exception/handler/EmployeeExceptionHandler.java
  src/main/java/com/greenatom/utils/exception/handler/ProductExceptionHandler.java
  src/main/java/com/greenatom/utils/exception/message/AuthErrorMessage.java
  src/main/java/com/greenatom/utils/exception/message/ClientErrorMessage.java
  src/main/java/com/greenatom/utils/exception/message/ErrorMessage.java
  src/main/java/com/greenatom/utils/generator/request/Constants.java
  src/main/java/com/greenatom/utils/generator/request/OrderGenerator.java
  src/main/java/com/greenatom/utils/generator/request/TextUtils.java
Labels: enhancement, refactoring
